// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VolleyMS.DataAccess;

#nullable disable

namespace VolleyMS.DataAccess.Migrations
{
    [DbContext(typeof(VolleyMsDbContext))]
    [Migration("20250928165913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubModelUserModel", b =>
                {
                    b.Property<Guid>("ClubModelsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserModelsId")
                        .HasColumnType("uuid");

                    b.HasKey("ClubModelsId", "UserModelsId");

                    b.HasIndex("UserModelsId");

                    b.ToTable("ClubModelUserModel");
                });

            modelBuilder.Entity("TaskModelUserModel", b =>
                {
                    b.Property<Guid>("ReceiverTaskModelsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserModel_receiversId")
                        .HasColumnType("uuid");

                    b.HasKey("ReceiverTaskModelsId", "UserModel_receiversId");

                    b.HasIndex("UserModel_receiversId");

                    b.ToTable("TaskModelUserModel");
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Entities.ClubModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarURL")
                        .HasColumnType("text");

                    b.Property<string>("BackGroundURL")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Entities.ContractModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BeginsFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClubModelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Currency")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MontlySalary")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubModelId");

                    b.HasIndex("UserId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Entities.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("userType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Models.CommentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("TaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Models.TaskModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PenaltyType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("integer");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("SenderId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ClubModelUserModel", b =>
                {
                    b.HasOne("VolleyMS.DataAccess.Entities.ClubModel", null)
                        .WithMany()
                        .HasForeignKey("ClubModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyMS.DataAccess.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskModelUserModel", b =>
                {
                    b.HasOne("VolleyMS.DataAccess.Models.TaskModel", null)
                        .WithMany()
                        .HasForeignKey("ReceiverTaskModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyMS.DataAccess.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserModel_receiversId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Entities.ContractModel", b =>
                {
                    b.HasOne("VolleyMS.DataAccess.Entities.ClubModel", "ClubModel")
                        .WithMany()
                        .HasForeignKey("ClubModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyMS.DataAccess.Entities.UserModel", "UserModel")
                        .WithMany("ContractModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Models.CommentModel", b =>
                {
                    b.HasOne("VolleyMS.DataAccess.Entities.UserModel", "UserModel_sender")
                        .WithMany("CommentModels")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyMS.DataAccess.Models.TaskModel", "TaskModel")
                        .WithMany("CommentModels")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskModel");

                    b.Navigation("UserModel_sender");
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Models.TaskModel", b =>
                {
                    b.HasOne("VolleyMS.DataAccess.Entities.ClubModel", "ClubModel")
                        .WithMany("TaskModels")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyMS.DataAccess.Entities.UserModel", "UserModel_sender")
                        .WithMany("SenderTaskModels")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubModel");

                    b.Navigation("UserModel_sender");
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Entities.ClubModel", b =>
                {
                    b.Navigation("TaskModels");
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Entities.UserModel", b =>
                {
                    b.Navigation("CommentModels");

                    b.Navigation("ContractModels");

                    b.Navigation("SenderTaskModels");
                });

            modelBuilder.Entity("VolleyMS.DataAccess.Models.TaskModel", b =>
                {
                    b.Navigation("CommentModels");
                });
#pragma warning restore 612, 618
        }
    }
}
